name: Check code with TypeScript & Lint

on:
  # push:
  #   branches:
  #     - 'master'
  # schedule:
  #   - cron:  '0 8 * * 0'
  workflow_dispatch:

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-22.04
          - ubicloud-standard-2
          - ubicloud-standard-4
          - ubicloud-standard-8
          - ubicloud-standard-16
          - ubicloud-standard-30
          - ubicloud-standard-2-ubuntu-2404
          - ubicloud-standard-4-ubuntu-2404
          - ubicloud-standard-8-ubuntu-2404
          - ubicloud-standard-2-arm
          - ubicloud-standard-4-arm
          - ubicloud-standard-8-arm
    # Uses larger hosted runner as it significantly decreases build times
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show cpu info
        run: lscpu

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.10.0
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i

      - name: Run TypeScript type check
        run: pnpm exec turbo run typecheck

      - name: Run Lint
        run: pnpm exec turbo run lint
